// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package stage

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go/aws"
	svcsdk "github.com/aws/aws-sdk-go/service/apigateway"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/apigateway-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &aws.JSONValue{}
	_ = &svcsdk.APIGateway{}
	_ = &svcapitypes.Stage{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.Stage
	resp, err = rm.sdkapi.GetStageWithContext(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetStage", err)
	if err != nil {
		if reqErr, ok := ackerr.AWSRequestFailure(err); ok && reqErr.StatusCode() == 404 {
			return nil, ackerr.NotFound
		}
		if awsErr, ok := ackerr.AWSError(err); ok && awsErr.Code() == "NotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.AccessLogSettings != nil {
		f0 := &svcapitypes.AccessLogSettings{}
		if resp.AccessLogSettings.DestinationArn != nil {
			f0.DestinationARN = resp.AccessLogSettings.DestinationArn
		}
		if resp.AccessLogSettings.Format != nil {
			f0.Format = resp.AccessLogSettings.Format
		}
		ko.Status.AccessLogSettings = f0
	} else {
		ko.Status.AccessLogSettings = nil
	}
	if resp.CacheClusterEnabled != nil {
		ko.Spec.CacheClusterEnabled = resp.CacheClusterEnabled
	} else {
		ko.Spec.CacheClusterEnabled = nil
	}
	if resp.CacheClusterSize != nil {
		ko.Spec.CacheClusterSize = resp.CacheClusterSize
	} else {
		ko.Spec.CacheClusterSize = nil
	}
	if resp.CacheClusterStatus != nil {
		ko.Status.CacheClusterStatus = resp.CacheClusterStatus
	} else {
		ko.Status.CacheClusterStatus = nil
	}
	if resp.CanarySettings != nil {
		f4 := &svcapitypes.CanarySettings{}
		if resp.CanarySettings.DeploymentId != nil {
			f4.DeploymentID = resp.CanarySettings.DeploymentId
		}
		if resp.CanarySettings.PercentTraffic != nil {
			f4.PercentTraffic = resp.CanarySettings.PercentTraffic
		}
		if resp.CanarySettings.StageVariableOverrides != nil {
			f4f2 := map[string]*string{}
			for f4f2key, f4f2valiter := range resp.CanarySettings.StageVariableOverrides {
				var f4f2val string
				f4f2val = *f4f2valiter
				f4f2[f4f2key] = &f4f2val
			}
			f4.StageVariableOverrides = f4f2
		}
		if resp.CanarySettings.UseStageCache != nil {
			f4.UseStageCache = resp.CanarySettings.UseStageCache
		}
		ko.Spec.CanarySettings = f4
	} else {
		ko.Spec.CanarySettings = nil
	}
	if resp.ClientCertificateId != nil {
		ko.Status.ClientCertificateID = resp.ClientCertificateId
	} else {
		ko.Status.ClientCertificateID = nil
	}
	if resp.CreatedDate != nil {
		ko.Status.CreatedDate = &metav1.Time{*resp.CreatedDate}
	} else {
		ko.Status.CreatedDate = nil
	}
	if resp.DeploymentId != nil {
		ko.Spec.DeploymentID = resp.DeploymentId
	} else {
		ko.Spec.DeploymentID = nil
	}
	if resp.Description != nil {
		ko.Spec.Description = resp.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.DocumentationVersion != nil {
		ko.Spec.DocumentationVersion = resp.DocumentationVersion
	} else {
		ko.Spec.DocumentationVersion = nil
	}
	if resp.LastUpdatedDate != nil {
		ko.Status.LastUpdatedDate = &metav1.Time{*resp.LastUpdatedDate}
	} else {
		ko.Status.LastUpdatedDate = nil
	}
	if resp.MethodSettings != nil {
		f11 := map[string]*svcapitypes.MethodSetting{}
		for f11key, f11valiter := range resp.MethodSettings {
			f11val := &svcapitypes.MethodSetting{}
			if f11valiter.CacheDataEncrypted != nil {
				f11val.CacheDataEncrypted = f11valiter.CacheDataEncrypted
			}
			if f11valiter.CacheTtlInSeconds != nil {
				f11val.CacheTTLInSeconds = f11valiter.CacheTtlInSeconds
			}
			if f11valiter.CachingEnabled != nil {
				f11val.CachingEnabled = f11valiter.CachingEnabled
			}
			if f11valiter.DataTraceEnabled != nil {
				f11val.DataTraceEnabled = f11valiter.DataTraceEnabled
			}
			if f11valiter.LoggingLevel != nil {
				f11val.LoggingLevel = f11valiter.LoggingLevel
			}
			if f11valiter.MetricsEnabled != nil {
				f11val.MetricsEnabled = f11valiter.MetricsEnabled
			}
			if f11valiter.RequireAuthorizationForCacheControl != nil {
				f11val.RequireAuthorizationForCacheControl = f11valiter.RequireAuthorizationForCacheControl
			}
			if f11valiter.ThrottlingBurstLimit != nil {
				f11val.ThrottlingBurstLimit = f11valiter.ThrottlingBurstLimit
			}
			if f11valiter.ThrottlingRateLimit != nil {
				f11val.ThrottlingRateLimit = f11valiter.ThrottlingRateLimit
			}
			if f11valiter.UnauthorizedCacheControlHeaderStrategy != nil {
				f11val.UnauthorizedCacheControlHeaderStrategy = f11valiter.UnauthorizedCacheControlHeaderStrategy
			}
			f11[f11key] = f11val
		}
		ko.Status.MethodSettings = f11
	} else {
		ko.Status.MethodSettings = nil
	}
	if resp.StageName != nil {
		ko.Spec.StageName = resp.StageName
	} else {
		ko.Spec.StageName = nil
	}
	if resp.Tags != nil {
		f13 := map[string]*string{}
		for f13key, f13valiter := range resp.Tags {
			var f13val string
			f13val = *f13valiter
			f13[f13key] = &f13val
		}
		ko.Spec.Tags = f13
	} else {
		ko.Spec.Tags = nil
	}
	if resp.TracingEnabled != nil {
		ko.Spec.TracingEnabled = resp.TracingEnabled
	} else {
		ko.Spec.TracingEnabled = nil
	}
	if resp.Variables != nil {
		f15 := map[string]*string{}
		for f15key, f15valiter := range resp.Variables {
			var f15val string
			f15val = *f15valiter
			f15[f15key] = &f15val
		}
		ko.Spec.Variables = f15
	} else {
		ko.Spec.Variables = nil
	}
	if resp.WebAclArn != nil {
		ko.Status.WebACLARN = resp.WebAclArn
	} else {
		ko.Status.WebACLARN = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Spec.RestAPIID == nil || r.ko.Spec.StageName == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetStageInput, error) {
	res := &svcsdk.GetStageInput{}

	if r.ko.Spec.RestAPIID != nil {
		res.SetRestApiId(*r.ko.Spec.RestAPIID)
	}
	if r.ko.Spec.StageName != nil {
		res.SetStageName(*r.ko.Spec.StageName)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.Stage
	_ = resp
	resp, err = rm.sdkapi.CreateStageWithContext(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateStage", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.AccessLogSettings != nil {
		f0 := &svcapitypes.AccessLogSettings{}
		if resp.AccessLogSettings.DestinationArn != nil {
			f0.DestinationARN = resp.AccessLogSettings.DestinationArn
		}
		if resp.AccessLogSettings.Format != nil {
			f0.Format = resp.AccessLogSettings.Format
		}
		ko.Status.AccessLogSettings = f0
	} else {
		ko.Status.AccessLogSettings = nil
	}
	if resp.CacheClusterEnabled != nil {
		ko.Spec.CacheClusterEnabled = resp.CacheClusterEnabled
	} else {
		ko.Spec.CacheClusterEnabled = nil
	}
	if resp.CacheClusterSize != nil {
		ko.Spec.CacheClusterSize = resp.CacheClusterSize
	} else {
		ko.Spec.CacheClusterSize = nil
	}
	if resp.CacheClusterStatus != nil {
		ko.Status.CacheClusterStatus = resp.CacheClusterStatus
	} else {
		ko.Status.CacheClusterStatus = nil
	}
	if resp.CanarySettings != nil {
		f4 := &svcapitypes.CanarySettings{}
		if resp.CanarySettings.DeploymentId != nil {
			f4.DeploymentID = resp.CanarySettings.DeploymentId
		}
		if resp.CanarySettings.PercentTraffic != nil {
			f4.PercentTraffic = resp.CanarySettings.PercentTraffic
		}
		if resp.CanarySettings.StageVariableOverrides != nil {
			f4f2 := map[string]*string{}
			for f4f2key, f4f2valiter := range resp.CanarySettings.StageVariableOverrides {
				var f4f2val string
				f4f2val = *f4f2valiter
				f4f2[f4f2key] = &f4f2val
			}
			f4.StageVariableOverrides = f4f2
		}
		if resp.CanarySettings.UseStageCache != nil {
			f4.UseStageCache = resp.CanarySettings.UseStageCache
		}
		ko.Spec.CanarySettings = f4
	} else {
		ko.Spec.CanarySettings = nil
	}
	if resp.ClientCertificateId != nil {
		ko.Status.ClientCertificateID = resp.ClientCertificateId
	} else {
		ko.Status.ClientCertificateID = nil
	}
	if resp.CreatedDate != nil {
		ko.Status.CreatedDate = &metav1.Time{*resp.CreatedDate}
	} else {
		ko.Status.CreatedDate = nil
	}
	if resp.DeploymentId != nil {
		ko.Spec.DeploymentID = resp.DeploymentId
	} else {
		ko.Spec.DeploymentID = nil
	}
	if resp.Description != nil {
		ko.Spec.Description = resp.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.DocumentationVersion != nil {
		ko.Spec.DocumentationVersion = resp.DocumentationVersion
	} else {
		ko.Spec.DocumentationVersion = nil
	}
	if resp.LastUpdatedDate != nil {
		ko.Status.LastUpdatedDate = &metav1.Time{*resp.LastUpdatedDate}
	} else {
		ko.Status.LastUpdatedDate = nil
	}
	if resp.MethodSettings != nil {
		f11 := map[string]*svcapitypes.MethodSetting{}
		for f11key, f11valiter := range resp.MethodSettings {
			f11val := &svcapitypes.MethodSetting{}
			if f11valiter.CacheDataEncrypted != nil {
				f11val.CacheDataEncrypted = f11valiter.CacheDataEncrypted
			}
			if f11valiter.CacheTtlInSeconds != nil {
				f11val.CacheTTLInSeconds = f11valiter.CacheTtlInSeconds
			}
			if f11valiter.CachingEnabled != nil {
				f11val.CachingEnabled = f11valiter.CachingEnabled
			}
			if f11valiter.DataTraceEnabled != nil {
				f11val.DataTraceEnabled = f11valiter.DataTraceEnabled
			}
			if f11valiter.LoggingLevel != nil {
				f11val.LoggingLevel = f11valiter.LoggingLevel
			}
			if f11valiter.MetricsEnabled != nil {
				f11val.MetricsEnabled = f11valiter.MetricsEnabled
			}
			if f11valiter.RequireAuthorizationForCacheControl != nil {
				f11val.RequireAuthorizationForCacheControl = f11valiter.RequireAuthorizationForCacheControl
			}
			if f11valiter.ThrottlingBurstLimit != nil {
				f11val.ThrottlingBurstLimit = f11valiter.ThrottlingBurstLimit
			}
			if f11valiter.ThrottlingRateLimit != nil {
				f11val.ThrottlingRateLimit = f11valiter.ThrottlingRateLimit
			}
			if f11valiter.UnauthorizedCacheControlHeaderStrategy != nil {
				f11val.UnauthorizedCacheControlHeaderStrategy = f11valiter.UnauthorizedCacheControlHeaderStrategy
			}
			f11[f11key] = f11val
		}
		ko.Status.MethodSettings = f11
	} else {
		ko.Status.MethodSettings = nil
	}
	if resp.StageName != nil {
		ko.Spec.StageName = resp.StageName
	} else {
		ko.Spec.StageName = nil
	}
	if resp.Tags != nil {
		f13 := map[string]*string{}
		for f13key, f13valiter := range resp.Tags {
			var f13val string
			f13val = *f13valiter
			f13[f13key] = &f13val
		}
		ko.Spec.Tags = f13
	} else {
		ko.Spec.Tags = nil
	}
	if resp.TracingEnabled != nil {
		ko.Spec.TracingEnabled = resp.TracingEnabled
	} else {
		ko.Spec.TracingEnabled = nil
	}
	if resp.Variables != nil {
		f15 := map[string]*string{}
		for f15key, f15valiter := range resp.Variables {
			var f15val string
			f15val = *f15valiter
			f15[f15key] = &f15val
		}
		ko.Spec.Variables = f15
	} else {
		ko.Spec.Variables = nil
	}
	if resp.WebAclArn != nil {
		ko.Status.WebACLARN = resp.WebAclArn
	} else {
		ko.Status.WebACLARN = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateStageInput, error) {
	res := &svcsdk.CreateStageInput{}

	if r.ko.Spec.CacheClusterEnabled != nil {
		res.SetCacheClusterEnabled(*r.ko.Spec.CacheClusterEnabled)
	}
	if r.ko.Spec.CacheClusterSize != nil {
		res.SetCacheClusterSize(*r.ko.Spec.CacheClusterSize)
	}
	if r.ko.Spec.CanarySettings != nil {
		f2 := &svcsdk.CanarySettings{}
		if r.ko.Spec.CanarySettings.DeploymentID != nil {
			f2.SetDeploymentId(*r.ko.Spec.CanarySettings.DeploymentID)
		}
		if r.ko.Spec.CanarySettings.PercentTraffic != nil {
			f2.SetPercentTraffic(*r.ko.Spec.CanarySettings.PercentTraffic)
		}
		if r.ko.Spec.CanarySettings.StageVariableOverrides != nil {
			f2f2 := map[string]*string{}
			for f2f2key, f2f2valiter := range r.ko.Spec.CanarySettings.StageVariableOverrides {
				var f2f2val string
				f2f2val = *f2f2valiter
				f2f2[f2f2key] = &f2f2val
			}
			f2.SetStageVariableOverrides(f2f2)
		}
		if r.ko.Spec.CanarySettings.UseStageCache != nil {
			f2.SetUseStageCache(*r.ko.Spec.CanarySettings.UseStageCache)
		}
		res.SetCanarySettings(f2)
	}
	if r.ko.Spec.DeploymentID != nil {
		res.SetDeploymentId(*r.ko.Spec.DeploymentID)
	}
	if r.ko.Spec.Description != nil {
		res.SetDescription(*r.ko.Spec.Description)
	}
	if r.ko.Spec.DocumentationVersion != nil {
		res.SetDocumentationVersion(*r.ko.Spec.DocumentationVersion)
	}
	if r.ko.Spec.RestAPIID != nil {
		res.SetRestApiId(*r.ko.Spec.RestAPIID)
	}
	if r.ko.Spec.StageName != nil {
		res.SetStageName(*r.ko.Spec.StageName)
	}
	if r.ko.Spec.Tags != nil {
		f8 := map[string]*string{}
		for f8key, f8valiter := range r.ko.Spec.Tags {
			var f8val string
			f8val = *f8valiter
			f8[f8key] = &f8val
		}
		res.SetTags(f8)
	}
	if r.ko.Spec.TracingEnabled != nil {
		res.SetTracingEnabled(*r.ko.Spec.TracingEnabled)
	}
	if r.ko.Spec.Variables != nil {
		f10 := map[string]*string{}
		for f10key, f10valiter := range r.ko.Spec.Variables {
			var f10val string
			f10val = *f10valiter
			f10[f10key] = &f10val
		}
		res.SetVariables(f10)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	if immutableFieldChanges := rm.getImmutableFieldChanges(delta); len(immutableFieldChanges) > 0 {
		msg := fmt.Sprintf("Immutable Spec fields have been modified: %s", strings.Join(immutableFieldChanges, ","))
		return nil, ackerr.NewTerminalError(fmt.Errorf(msg))
	}
	if delta.DifferentAt("Spec.Tags") {
		resourceARN, err := arnForResource(desired.ko)
		if err != nil {
			return nil, fmt.Errorf("applying tags: %w", err)
		}
		if err := syncTags(ctx, rm.sdkapi, rm.metrics, resourceARN, desired.ko.Spec.Tags, latest.ko.Spec.Tags); err != nil {
			return nil, err
		}
	}
	if !delta.DifferentExcept("Spec.Tags") {
		return desired, nil
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}
	updateStageInput(desired, latest, input, delta)

	var resp *svcsdk.Stage
	_ = resp
	resp, err = rm.sdkapi.UpdateStageWithContext(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateStage", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.AccessLogSettings != nil {
		f0 := &svcapitypes.AccessLogSettings{}
		if resp.AccessLogSettings.DestinationArn != nil {
			f0.DestinationARN = resp.AccessLogSettings.DestinationArn
		}
		if resp.AccessLogSettings.Format != nil {
			f0.Format = resp.AccessLogSettings.Format
		}
		ko.Status.AccessLogSettings = f0
	} else {
		ko.Status.AccessLogSettings = nil
	}
	if resp.CacheClusterEnabled != nil {
		ko.Spec.CacheClusterEnabled = resp.CacheClusterEnabled
	} else {
		ko.Spec.CacheClusterEnabled = nil
	}
	if resp.CacheClusterSize != nil {
		ko.Spec.CacheClusterSize = resp.CacheClusterSize
	} else {
		ko.Spec.CacheClusterSize = nil
	}
	if resp.CacheClusterStatus != nil {
		ko.Status.CacheClusterStatus = resp.CacheClusterStatus
	} else {
		ko.Status.CacheClusterStatus = nil
	}
	if resp.CanarySettings != nil {
		f4 := &svcapitypes.CanarySettings{}
		if resp.CanarySettings.DeploymentId != nil {
			f4.DeploymentID = resp.CanarySettings.DeploymentId
		}
		if resp.CanarySettings.PercentTraffic != nil {
			f4.PercentTraffic = resp.CanarySettings.PercentTraffic
		}
		if resp.CanarySettings.StageVariableOverrides != nil {
			f4f2 := map[string]*string{}
			for f4f2key, f4f2valiter := range resp.CanarySettings.StageVariableOverrides {
				var f4f2val string
				f4f2val = *f4f2valiter
				f4f2[f4f2key] = &f4f2val
			}
			f4.StageVariableOverrides = f4f2
		}
		if resp.CanarySettings.UseStageCache != nil {
			f4.UseStageCache = resp.CanarySettings.UseStageCache
		}
		ko.Spec.CanarySettings = f4
	} else {
		ko.Spec.CanarySettings = nil
	}
	if resp.ClientCertificateId != nil {
		ko.Status.ClientCertificateID = resp.ClientCertificateId
	} else {
		ko.Status.ClientCertificateID = nil
	}
	if resp.CreatedDate != nil {
		ko.Status.CreatedDate = &metav1.Time{*resp.CreatedDate}
	} else {
		ko.Status.CreatedDate = nil
	}
	if resp.DeploymentId != nil {
		ko.Spec.DeploymentID = resp.DeploymentId
	} else {
		ko.Spec.DeploymentID = nil
	}
	if resp.Description != nil {
		ko.Spec.Description = resp.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.DocumentationVersion != nil {
		ko.Spec.DocumentationVersion = resp.DocumentationVersion
	} else {
		ko.Spec.DocumentationVersion = nil
	}
	if resp.LastUpdatedDate != nil {
		ko.Status.LastUpdatedDate = &metav1.Time{*resp.LastUpdatedDate}
	} else {
		ko.Status.LastUpdatedDate = nil
	}
	if resp.MethodSettings != nil {
		f11 := map[string]*svcapitypes.MethodSetting{}
		for f11key, f11valiter := range resp.MethodSettings {
			f11val := &svcapitypes.MethodSetting{}
			if f11valiter.CacheDataEncrypted != nil {
				f11val.CacheDataEncrypted = f11valiter.CacheDataEncrypted
			}
			if f11valiter.CacheTtlInSeconds != nil {
				f11val.CacheTTLInSeconds = f11valiter.CacheTtlInSeconds
			}
			if f11valiter.CachingEnabled != nil {
				f11val.CachingEnabled = f11valiter.CachingEnabled
			}
			if f11valiter.DataTraceEnabled != nil {
				f11val.DataTraceEnabled = f11valiter.DataTraceEnabled
			}
			if f11valiter.LoggingLevel != nil {
				f11val.LoggingLevel = f11valiter.LoggingLevel
			}
			if f11valiter.MetricsEnabled != nil {
				f11val.MetricsEnabled = f11valiter.MetricsEnabled
			}
			if f11valiter.RequireAuthorizationForCacheControl != nil {
				f11val.RequireAuthorizationForCacheControl = f11valiter.RequireAuthorizationForCacheControl
			}
			if f11valiter.ThrottlingBurstLimit != nil {
				f11val.ThrottlingBurstLimit = f11valiter.ThrottlingBurstLimit
			}
			if f11valiter.ThrottlingRateLimit != nil {
				f11val.ThrottlingRateLimit = f11valiter.ThrottlingRateLimit
			}
			if f11valiter.UnauthorizedCacheControlHeaderStrategy != nil {
				f11val.UnauthorizedCacheControlHeaderStrategy = f11valiter.UnauthorizedCacheControlHeaderStrategy
			}
			f11[f11key] = f11val
		}
		ko.Status.MethodSettings = f11
	} else {
		ko.Status.MethodSettings = nil
	}
	if resp.StageName != nil {
		ko.Spec.StageName = resp.StageName
	} else {
		ko.Spec.StageName = nil
	}
	if resp.Tags != nil {
		f13 := map[string]*string{}
		for f13key, f13valiter := range resp.Tags {
			var f13val string
			f13val = *f13valiter
			f13[f13key] = &f13val
		}
		ko.Spec.Tags = f13
	} else {
		ko.Spec.Tags = nil
	}
	if resp.TracingEnabled != nil {
		ko.Spec.TracingEnabled = resp.TracingEnabled
	} else {
		ko.Spec.TracingEnabled = nil
	}
	if resp.Variables != nil {
		f15 := map[string]*string{}
		for f15key, f15valiter := range resp.Variables {
			var f15val string
			f15val = *f15valiter
			f15[f15key] = &f15val
		}
		ko.Spec.Variables = f15
	} else {
		ko.Spec.Variables = nil
	}
	if resp.WebAclArn != nil {
		ko.Status.WebACLARN = resp.WebAclArn
	} else {
		ko.Status.WebACLARN = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateStageInput, error) {
	res := &svcsdk.UpdateStageInput{}

	if r.ko.Spec.RestAPIID != nil {
		res.SetRestApiId(*r.ko.Spec.RestAPIID)
	}
	if r.ko.Spec.StageName != nil {
		res.SetStageName(*r.ko.Spec.StageName)
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteStageOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteStageWithContext(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteStage", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteStageInput, error) {
	res := &svcsdk.DeleteStageInput{}

	if r.ko.Spec.RestAPIID != nil {
		res.SetRestApiId(*r.ko.Spec.RestAPIID)
	}
	if r.ko.Spec.StageName != nil {
		res.SetStageName(*r.ko.Spec.StageName)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Stage,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}
	awsErr, ok := ackerr.AWSError(err)
	if !ok {
		return false
	}
	switch awsErr.Code() {
	case "BadRequestException",
		"ConflictException",
		"NotFoundException",
		"InvalidParameter":
		return true
	default:
		return false
	}
}

// getImmutableFieldChanges returns list of immutable fields from the
func (rm *resourceManager) getImmutableFieldChanges(
	delta *ackcompare.Delta,
) []string {
	var fields []string
	if delta.DifferentAt("Spec.RestAPIID") {
		fields = append(fields, "RestAPIID")
	}
	if delta.DifferentAt("Spec.StageName") {
		fields = append(fields, "StageName")
	}

	return fields
}
