---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-apigateway-reader
  namespace: default
rules:
- apiGroups:
  - apigateway.services.k8s.aws
  resources:
  - apimethodresponses
  - integrations
  - methods
  - resources
  - restapis
  - stages
  - vpclinks
  verbs:
  - get
  - list
  - watch
