// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package api_key

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.CustomerID, b.ko.Spec.CustomerID) {
		delta.Add("Spec.CustomerID", a.ko.Spec.CustomerID, b.ko.Spec.CustomerID)
	} else if a.ko.Spec.CustomerID != nil && b.ko.Spec.CustomerID != nil {
		if *a.ko.Spec.CustomerID != *b.ko.Spec.CustomerID {
			delta.Add("Spec.CustomerID", a.ko.Spec.CustomerID, b.ko.Spec.CustomerID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Description, b.ko.Spec.Description) {
		delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
	} else if a.ko.Spec.Description != nil && b.ko.Spec.Description != nil {
		if *a.ko.Spec.Description != *b.ko.Spec.Description {
			delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Enabled, b.ko.Spec.Enabled) {
		delta.Add("Spec.Enabled", a.ko.Spec.Enabled, b.ko.Spec.Enabled)
	} else if a.ko.Spec.Enabled != nil && b.ko.Spec.Enabled != nil {
		if *a.ko.Spec.Enabled != *b.ko.Spec.Enabled {
			delta.Add("Spec.Enabled", a.ko.Spec.Enabled, b.ko.Spec.Enabled)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.GenerateDistinctID, b.ko.Spec.GenerateDistinctID) {
		delta.Add("Spec.GenerateDistinctID", a.ko.Spec.GenerateDistinctID, b.ko.Spec.GenerateDistinctID)
	} else if a.ko.Spec.GenerateDistinctID != nil && b.ko.Spec.GenerateDistinctID != nil {
		if *a.ko.Spec.GenerateDistinctID != *b.ko.Spec.GenerateDistinctID {
			delta.Add("Spec.GenerateDistinctID", a.ko.Spec.GenerateDistinctID, b.ko.Spec.GenerateDistinctID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if len(a.ko.Spec.StageKeys) != len(b.ko.Spec.StageKeys) {
		delta.Add("Spec.StageKeys", a.ko.Spec.StageKeys, b.ko.Spec.StageKeys)
	} else if len(a.ko.Spec.StageKeys) > 0 {
		if !reflect.DeepEqual(a.ko.Spec.StageKeys, b.ko.Spec.StageKeys) {
			delta.Add("Spec.StageKeys", a.ko.Spec.StageKeys, b.ko.Spec.StageKeys)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Value, b.ko.Spec.Value) {
		delta.Add("Spec.Value", a.ko.Spec.Value, b.ko.Spec.Value)
	} else if a.ko.Spec.Value != nil && b.ko.Spec.Value != nil {
		if *a.ko.Spec.Value != *b.ko.Spec.Value {
			delta.Add("Spec.Value", a.ko.Spec.Value, b.ko.Spec.Value)
		}
	}

	return delta
}
